### PR TITLE
Added Submission criteria component

### PR DESCRIPTION
**Pull request by Melo04**

### CODE REVIEW

**Comment by Laikaiyong** [comment]
Dark mode is not optimized, recommended to change the color to fit in dark mode.

Light mode is fine imo

**Review by Laikaiyong — CHANGES_REQUESTED** [review]
@Melo04 
Dark mode is not optimized, recommended to change the color to fit in dark mode.

Light mode is fine imo

**Comment by Melo04** [comment]
Updated submission criteria component

**Comment by Melo04** [comment]
Updated dark mode

**Review by Laikaiyong — APPROVED** [review]
Good to go, great stuff!!

**Pull request merged**
