### PR TITLE
Updated kickoff event page

### PR DESCRIPTION
**Pull request by zongqiooi**

### CODE REVIEW

**Comment by kayinleong** [comment]
I think need to change the navbar to indicate where we are. Other than that, lgtm.

**Review by kayinleong — CHANGES_REQUESTED** [review]
I think need to change the navbar to indicate where we are. Other than that, lgtm.

**Comment by zongqiooi** [comment]
Fixed navbar to indicate current page

**Review by Laikaiyong — APPROVED** [review]
good to go

**Pull request merged**
